apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.pgadmin.config.script_name }}`)
    kind: Rule
    services:
    - name: pgadmin-service
      port: {{ .Values.pgadmin.service.port }}
    middlewares:
      - name: traefik-auth-admin-middleware
      - name: https-redirect
  tls:
    certResolver: letsencrypt